house_power_consume = read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)

house_power_consume = transform(house_power_consume, Date = as.Date(Date, "%d/%m/%Y"))
house_power_consume = subset(house_power_consume, Date == "2007-02-02" | Date == "2007-02-01")
house_power_consume = transform(house_power_consume, Global_active_power = as.numeric(Global_active_power))
house_power_consume$Time = paste(house_power_consume$Date, house_power_consume$Time, sep = " ")
house_power_consume = transform(house_power_consume, Time = strptime(Time, "%Y-%m-%d %H:%M:%S"))
par(mfrow = c(1,1))
with(house_power_consume, plot(Time, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.copy(png, file = "plot2.png")
dev.off()