house_power_consume = read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)

house_power_consume = transform(house_power_consume, Date = as.Date(Date, "%d/%m/%Y"))
house_power_consume = subset(house_power_consume, Date == "2007-02-02" | Date == "2007-02-01")
house_power_consume = transform(house_power_consume, Global_active_power = as.numeric(Global_active_power))
house_power_consume$Time = paste(house_power_consume$Date, house_power_consume$Time, sep = " ")
house_power_consume = transform(house_power_consume, Time = strptime(Time, "%Y-%m-%d %H:%M:%S"))
house_power_consume = transform(house_power_consume, Sub_metering_1 = as.numeric(Sub_metering_1))
house_power_consume = transform(house_power_consume, Sub_metering_2 = as.numeric(Sub_metering_2))
house_power_consume = transform(house_power_consume, Sub_metering_3 = as.numeric(Sub_metering_3))

with(house_power_consume, plot(Time, Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering"))
with(house_power_consume, lines(Time, Sub_metering_2, type = "l", col = "red"))
with(house_power_consume, lines(Time, Sub_metering_3, type = "l", col = "blue"))
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, y.intersp = 0.4, text.font = 1, cex = 0.8)
dev.copy(png, file = "plot3.png")
dev.off()